### ISSUE TITLE
When I want to create an offer or demand and switch the device to a horicontal or vertical view, the index page will be shown and my inputs will be erased.

### ISSUE THREAD

**Issue by sasfeld** [HTW-Projekt-2014-Commercetools/neeedo-android#9]
Reproduce: 
- Click Create demand or Create offer.
- Make some inputs.
- Switch the device orientation (e.g. to horicontal).
- The index page will be shown and the inputs will be erased.

Desired solution:
- The Create demand / Create offer should be shown. 
- The inputs should not be erased.

**Comment by TIIUNDER** [comment]
Fixed for now using a workaround: landscape mode disabled ;-)
